# Generated by Django 6.0.2 on 2026-02-26 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bride_name', models.CharField(blank=True, max_length=100, null=True)),
                ('groom_name', models.CharField(blank=True, max_length=100, null=True)),
                ('wedding_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('story', models.TextField(blank=True, null=True)),
                ('herStory', models.TextField(blank=True, null=True)),
                ('hisStory', models.TextField(blank=True, null=True)),
                ('how_we_met', models.TextField(blank=True, null=True)),
                ('dateOfMeet', models.DateField(blank=True, null=True)),
                ('first_date', models.TextField(blank=True, null=True)),
                ('dateOfDate', models.DateField(blank=True, null=True)),
                ('proposal', models.TextField(blank=True, null=True)),
                ('dateOfProposal', models.DateField(blank=True, null=True)),
                ('engagement', models.TextField(blank=True, null=True)),
                ('dateOfEngagement', models.DateField(blank=True, null=True)),
                ('marriage', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attending', models.BooleanField(null=True)),
                ('number_of_guests', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ForeverLove.guest')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ForeverLove.wedding')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herImage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('hisImage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('meet', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('engagement', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('first_date', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('proposal', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('marriage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('gallery1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('gallery2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('gallery3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('gallery4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('gallery5', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('gallery6', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('wedding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ForeverLove.wedding')),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='wedding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ForeverLove.wedding'),
        ),
    ]
