# Generated by Django 6.0.2 on 2026-02-28 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ForeverLove', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='engagement',
            new_name='engagementImg',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='first_date',
            new_name='first_dateImg',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='marriage',
            new_name='marriageImg',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='meet',
            new_name='meetImg',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='proposal',
            new_name='proposalImg',
        ),
    ]
